version: '3.7'

services:
  antee-pwa:
    image: antee-pwa:latest
    container_name: antee-pwa-container
    build:
      context: ../..
      dockerfile: packages/antee/Dockerfile
      target: prod
      args:
        - PUBLIC_URL=/
    ports:
      - 80:80
